### ISSUE TITLE
Xia handler causing chunk reloading

### ISSUE THREAD

**Issue by LemADEC** [Tamaized/VoidCraft#102]
As of VoidCraft-1.10.2-0.17.8.jar, forge reports 5% CPU time taken by Xia dimension when a player is inside it.
As observed with a profiler, it appears to be related to chunk loading, maybe the range involved in getEntitiesWithinAABB is too big?

![image](https://cloud.githubusercontent.com/assets/4776032/23880281/facc4e10-0852-11e7-9462-49123e7c6754.png)

**Comment by Tamaized** [comment]
This wouldn't be dealing with how chunks are loaded, it's just getting a list of entities with the aabb (which is a small radius), the locations would be in already loaded chunks anyway. the castle isnt very big and all 3 aabbs are pretty close

**Comment by Tamaized** [comment]
RFTools uses the same aabb based checks for their shield blocks, those would cause the same effect.

**Comment by LemADEC** [comment]
Actually, the profiler shows something different than chunkloading.

**Comment by Tamaized** [comment]
The image provided shows my call to world.getEntitiesWithinAABB() yea, but I'm not quite sure what I can do about it to improve performance.

**Comment by Tamaized** [comment]
I went ahead and made sure if I needed to check if the chunks were loaded or not and it turns out World#getEntitiesWithinAABB already does this check for me. So there's nothing more I can do here.
![capture](https://cloud.githubusercontent.com/assets/9671313/23925657/83019c02-08cd-11e7-9ad2-6e448c349e2f.PNG)

**Comment by LemADEC** [comment]
It's not chunkloading from getEntitiesWithinAABB(), my initial assumption was incorrect.

According to the profiler, it's lagging while scanning the chunks. I imagine several factors that could cause this:
1- we're checking too many chunks
2- there's too many chunks loaded already
3- the Handler is called several times per tick

I suppose the 3 checks are done but the bounding boxes are at most 37x23, so it's not the 1-.

XiaCastleLogicHandler is only instanciated once through the WorldProvider, and called through WorldProvided::onWorldUpdateEntities(). So 3- is possible in case of world leak. The latest would have to be pretty massive, or a forge bug so it doesn't seem right.

So we're down to 2-, which is too many chunks loaded.
The castle schematic seems reasonably sized, so that's not it. Something else would be loading chunks, but only impacts significantly Xia dimension, so it's off too.

so I guess, it'll require some logs and poking around to understand what's going on here.

**Comment by Tamaized** [comment]
On a side note, there's actually only 2 AABBs that are running on a fresh Xia dimension before the player does any progress. That would be these two: https://github.com/Tamaized/VoidCraft/blob/1.11.2/src/main/java/Tamaized/Voidcraft/xiaCastle/logic/XiaCastleLogicHandler.java#L75-L76

that's an area coverage of 10x2x6 for the first (we're using X by Y by Z in terms of distance order)
and an area of 8x2x20 for the second.

**Comment by Tamaized** [comment]
As for the possibility of a leak and more instances being created, well it's handled the same exact way as the DragonFightManager located in WorldProviderEnd meaning if there were some sort of leak, you'd most likely see it from that as well. So doubt it's that.

**Comment by LemADEC** [comment]
From a quick test in SMP, there's also lag from TheEnd when players are in it.
1 or 2 players in TheEnd, standing in god mode on top of pillar:
![image](https://cloud.githubusercontent.com/assets/4776032/23930401/662e300e-092c-11e7-8cbe-c8570fe7cb2a.png)
No player in TheEnd:
![image](https://cloud.githubusercontent.com/assets/4776032/23930418/7c207386-092c-11e7-9338-01d19adf3ba5.png)

I'll have to confirm that in single player.
From a quick check, nothing specific shows up in the profiler.

**Comment by Tamaized** [comment]
Wouldn't be due to my mod, it may be safe to assume that loaded dimensions just use more processing power because of the now loaded chunks. But that's pretty normal.

**Comment by Tamaized** [comment]
I also want to point out, if your overall tick time is less than or equal to 50ms you have nothing at all to worry about. 1000ms to a second, 1000ms/20ticks is 50ms

**Comment by LemADEC** [comment]
Those measures are with a single IDLE player online with no tech mods. Having a total of 24ms in those circunstances is bad, especially when each added player increase that by 15+ms.

**Comment by Tamaized** [comment]
Well, no idea what to tell you. My mod doesn't touch anything in the end besides world gen for ores but that wouldn't cause tps issues.

**Comment by LemADEC** [comment]
Following check with and without VoidCraft in single player, lag in the end doesn't come from VoidCraft.
I'm running out of ideas on this one.

**Comment by Tamaized** [comment]
I believe it's just the game itself. Does it occur without mods.

**Comment by LemADEC** [comment]
I've tried removing mods in single player, measuring with /forge tps: it's inconclusive and lack details to move further.
It feels like too much chunks are loaded but at the same time they're not.
It feels like world objects are being "held" but dimensions are properly unloading.
