### ISSUE TITLE
[Suggestion] Remove / make configurable skin validation

### ISSUE THREAD

**Issue by Aphyxia** [Tamaized/VoidCraft#106]
The skin validation part of launching Forge takes quite a bit of time. I don't know what the skins are used for but I don't think I gain anything of value by having Vazkii or direwolf20 skinned characters in my game. That is for meme loving children, I'd much rather have quicker loading times. I possible, a config option for it would be nice.

**Comment by Tamaized** [comment]
I've already moved it onto it's own dameon thread and no longer effects the load time itself. though not sure when I plan to push a new update out as i'm working on something a bit large right now for the mod.

**Comment by Tamaized** [comment]
And here's the commit with the changes: cceadb4be2f8dc582aa5308a4929314bbf99eb42
