### ISSUE TITLE
"Not enough spell material to cast null"

### ISSUE THREAD

**Issue by ShelLuser** [Tamaized/VoidCraft#111]
I'm currently checking out the mod to see if I should add it to my gameplay (like it so far) and I just managed to unlock the spells button. However, if I simply try to use the Vade Mecum without selecting any kind of word then you'll the error mentioned in the title.

I believe this to be a bug because I'm all too well familiar with "null" :)

Right now my assumption is that I haven't selected any spell, still try to cast one and instead of telling me that I don't have a spell it's referring to my mana instead.

How to reproduce:
- Start a new game.
- Get the Mecum
- Shift right click to change the color

=> On a side note I prefer "sneak (or crouch) right click" because plenty of players could have remapped this ;)

- Try to cast something by right clicking

This will generate the error shown in the title.

**Comment by Tamaized** [comment]
Yup, known issue. I'll go ahead and leave this open till I decide to fix it.
