### ISSUE TITLE
Vade Mecum suggestion

### ISSUE THREAD

**Issue by ShelLuser** [Tamaized/VoidCraft#112]
I'm slowly, but steadily, _really_ starting to grow a liking to your mod. Small sidestep: at first I was a bit surprised to learn that in order to play you had to finish Minecraft (you need the End for Void crystals). Then I realized: "I got other mods too" (I have a habit of not mentioning to avoid unwanted advertising). In short: I got my crystals "another" way :)

Here's my concern: "Voidic ritual blocks". It shows a 3x3 pattern which I believe could be easily confused with the crafting grid (matter of opinion, I'm well aware!). But to put more emphasis on building over crafting I'd like to suggest the following:

(from the Void Vade Mecum (awesome read so far by the way))

from: Voidic Ritual Blocks

"To activate such a ritual simply construct one shown, then right click the Ritual Block with the Vade Mecum in hand."

My suggestion:

"To activate such a ritual simply place as shown, then right click the Ritual Block with ...."

This puts more emphasis on placing (blocks) over crafting / building.

Yes, I'll go on the record: at first I also approached this as a recipe ;)

I'm seriously liking this so far. Right now I'm experimenting in semi-creative but the way this is going I'm definitely going to use this in my soon-to-be-restarted tech survival.

**Comment by ShelLuser** [comment]
Please ignore this suggestion... meh..  "don't drink and void" :P

Sorry but I just discovered that it _is_ a crafting mechanic, a working one at that and yeah..  My bad.

**Comment by Tamaized** [comment]
Haha, I understand what got you confused though.

**Comment by Tamaized** [comment]
however, if you feel something can be worded better you're more than welcome to submit a pull request, these are all stored in my lang file. submitting issues is perfectly fine as well.

**Comment by ShelLuser** [comment]
I'll stick to submitting because the pull request feature seems very arcane to me. Thanks for the quick response by the way.
