### ISSUE TITLE
Suggestion: balance game progress

### ISSUE THREAD

**Issue by ShelLuser** [Tamaized/VoidCraft#114]
This is a one out of 2 suggestion by the way, sort off.

Here's my concern...  When you get to acquiring words of power all is relatively simple. The void ritual block can be tricky to get, but it's all doable (all it takes is a trip to the end, which, when combining your mod with others, doesn't have to be too problematic) (no spam but... portable transport devices for the win ;)).

But the next step in the Mecum ("throwable potions") is a pretty steep step to take. It sounds all too easy (alchemical device) but what that doesn't tell you is that you need to perform quite a few steps to get it...
- Void infusion altar (which requires Void exploration to get void inflused cloth, so far this wasn't required). 
- Void blast furnace (which requires the molten void chain part, also kind of hard to get).
- ... because the chain part also requires a smelting process. (doesn't that require the blast furnace in itself?). Note: I know it doesn't, I tried and I smelted a chain using a regular furnace.

Thing is: I would expect the Mysteries of the Void to guide players into the Void before challenging them into getting these void machineries. Just as I also expected it to tell me that I could smelt the chain using a regular furnace.

I have a way with words so to speak, so if there's something I can do to help out then please let me know.

**Comment by Tamaized** [comment]
The mysteries of the void is actually pretty new and I still plan to expand upon it. The current system as it stands now was basically a way to allow you to turn voidic infusion around and make it powerful for yourself instead of it slowly killing you, without obtaining the powers and such, the void becomes quite brutal.

But yes, in short it's brand new and is lacking full content but things will be added in the future.

**Comment by Tamaized** [comment]
A note on the potions though, they were just a silly addition I decided to add, the idea popped up in my head and I fully implemented them within 5 minutes lol. They serve no purpose to progression.

**Comment by Tamaized** [comment]
One last thing, just a small correction, Void Cloth actually doesn't require you to enter the Void at all. They can be aquired from the Void Lich which spawns in swampland biomes.

**Comment by Tamaized** [comment]
Gonna close this one as it's basically already in #110
