### ISSUE TITLE
Camera issues while in reverse chase cam: Voidic Infusion overlay randomly appears

### ISSUE THREAD

**Issue by kragnoth** [Tamaized/VoidCraft#116]
When in survival and using reverse chasecam (press f5 a couple times) I get the voidic infusion overlay.  I also get it in random chunks and random heights while in spectator mode (/gamemode spectator)

This happens in 1.11.2 minecraft with version 17.9 of voidcraft.

**Comment by Tamaized** [comment]
is this on a server or single player?

**Comment by Tamaized** [comment]
Tested on both the 1.10.2 branch and the 1.11.2 branch, wasn't able to reproduce this on both single player and a dedicated server.

**Comment by kragnoth** [comment]
weird, I get this on single player in 1.11.2, and I tracked the texture to your mod.  I'll try it again with the latest release and report back.  Maybe it is a mod interaction with embers or some other mod that adds random overlays.  Only happens in reverse camera or /gamerule spectator though, so I'll deal.

**Comment by Tamaized** [comment]
The only thing I can think of that could cause this would be someone messing with the alpha channel on glColor during overlay drawing or a weird packet issue but you'd only see the packet issue i'm thinking of on a dedicated server but we already know that's not the case. For the drawing bit, that still shouldn't effect my overlay with how i'm drawing so i'm not really sure here.

**Comment by Tamaized** [comment]
And here's the class that handles the drawing, pretty standard nothing special is going on here that would be related to the causes you mention.
https://github.com/Tamaized/VoidCraft/blob/1.11.2/src/main/java/Tamaized/Voidcraft/client/ClientInfusionOverlayRender.java

**Comment by MokahTGS** [comment]
well unfortunately its easier to turn off Voidcraft then it is to go through all 275 other mods to find out what is causing it.  Best of luck, but until this is fixed we can't have it active in our mod pack.  It happens randomly and completely shuts down everyone on the test server.  We have to restart and even then there are times when it won't go away.

**Comment by Tamaized** [comment]
@MokahTGS Wait wait wait, does that mean when the issue occurs it effects everyone playing on the server at once?
