### ISSUE TITLE
[Question] Xia and Quest Books

### ISSUE THREAD

**Issue by MokahTGS** [Tamaized/VoidCraft#122]
I'm in the process of making a mod pack that has a lot of bosses to kill for quests.  I love the way you've made these bosses, but I'm not sure they will work for the standard kill type quest, since you don't use standard kill mechanics to beat them.  Xol and Dol, you don't even fight.

So the question is, when you beat the bosses, are there items you get that we could use as quest requirements/tasks in an HQM quest?  I'm not sure they drop anything that I could use, also I don't know anything about the Xia fight since there doesn't seem to be any video playthroughs of it.

**Comment by Tamaized** [comment]
Right, so after beating every boss in the Xia dimension you are sent to an area within the dimension known as the StarForge. A place where you craft end game tools and weapons for the mod. When you reach this area a chest spawns with Quori Fragments inside. The amount depends on how many players were in the Xia dimension when the final boss dies. So yes, you get a single type of item from all of the bosses combined. You also get armor after Xia's first form is defeated which grants flight but it's to allow you to fight his second form. Players get to keep this armor.

**Comment by MokahTGS** [comment]
Can you fight Xia before the other bosses or is there a progression.  Also, if i make one of those fragments as the quest item needed, can you get more?

**Comment by Tamaized** [comment]
It's an actual system embedded into the Dimension itself (think The End's dragon fight). The first two boss fights must be completed first before the door to Xia's area opens up, order doesn't matter for just those first two. But no, you can't skip anything and go directly to Xia himself nor can you spawn in the entities (they'll despawn as they're missing key data which is set in code from my system).

After you get the Fragment you can re-enter the dimension again and refight them all for another, yes. You actually need a decent amount of fragments for StarForged crafting.
