### ISSUE TITLE
[1.11.2] Void Shield Issues

### ISSUE THREAD

**Issue by Leafygreens97** [Tamaized/VoidCraft#126]
I think I may understand what is happening behind the first issue, which is that the shield's durability degrades rapidly while blocking with it in the upper Void, where you need Plenum to survive. It will continue to do so after you have stopped holding down right click until you pull it out of your hand in your inventory or drop it. Perhaps it is trying to "block" the void damage you would take had Plenum not been making you immune? Which leads me to my other issue.

Every time the Void Shield Breaks, it crashes the game. It breaks from the above mentioned issue if left alone, obviously, but even if it breaks from normal use, it crashes the game. I provided a crash report for each instance below, respectively, if you need both of them:

Shield breaking from use in the upper Void:
[crash-2017-04-09_15.54.45-server.txt](https://github.com/Tamaized/VoidCraft/files/908591/crash-2017-04-09_15.54.45-server.txt)
Shield breaking from normal use (allowing a Chained Spectre to break it):
[crash-2017-04-09_15.57.03-server.txt](https://github.com/Tamaized/VoidCraft/files/908592/crash-2017-04-09_15.57.03-server.txt)

**Comment by Tamaized** [comment]
Ahh silly me, ItemStack null issue, I assume the crash doesn't exist in 1.10.2.

As for the first issue, i'll look into it.
