### ISSUE TITLE
[1.11.2] Corrupted Pawn nameplate does not get translated correctly - screenshot included

### ISSUE THREAD

**Issue by PrinceOfAmber** [Tamaized/VoidCraft#127]
As you can see, it says "entity.VoidBoss.name" . I noticed in the language file it says "entity.voidcraft.VoidBoss.name=Corrupted Pawn

![vc](https://cloud.githubusercontent.com/assets/621529/24841734/78ed707a-1d3f-11e7-894d-86992dc1c419.png)

**Comment by Tamaized** [comment]
I swear I've fixed this at least 100 times now >.> switching between my 1.11 and 1.10 branches really screws with things.

**Comment by Tamaized** [comment]
Actually I take that back, this was due to my lang file missing a few things and I had JUST fixed this before you sent the issue haha

17218607c9892fb63edc4a201784e4f2fa8dd273
