### ISSUE TITLE
Purple Sleep Overlay - Turning it off

### ISSUE THREAD

**Issue by MokahTGS** [Tamaized/VoidCraft#128]
Is it Voidcraft that adds the purple overlay over the screen when you sleep?  How can I turn it off?  It sometimes gets stuck on my screen and won't go away...forcing me to crash my game.

**Comment by MokahTGS** [comment]
How would I figure out what mod is doing that?  Would it be something that messes with the sleep code?

**Comment by Tamaized** [comment]
removing mods besides my mods until the problem goes away (backup the world first so you can go back to it after putting the mods back) but once the offending mod is found then it can be reported back to here and I can investigate the issue further.

**Comment by Tamaized** [comment]
Referencing this as it seems to be related: #116
