### ISSUE TITLE
Unlocking the Word: Ice Spike Error

### ISSUE THREAD

**Issue by SolSavvy** [Tamaized/VoidCraft#129]
I've arranged the materials properly and even lifted the multi-block structure one level above the ground, but the book still does not recognize the ritual. Why could this be? it only requires Ice blocks and a ritual block in the corner of the first layer.

**Comment by Tamaized** [comment]
it's possible a specific orientation is broken that needs fixing, try it in another way (basically rotate the entire structure), I'll look into this when I can though.

**Comment by SolSavvy** [comment]
I tried placing the voidic ritual block last, and that seemed to fix it

**Comment by Tamaized** [comment]
exact same orientation?

**Comment by Tamaized** [comment]
Right, through my own testing I just confirmed specific orientations are bugged.
