### ISSUE TITLE
Cannot reach the top of The Void without dying to "Falling Out Of the World" (Void Cities non-accessible)

### ISSUE THREAD

**Issue by SolSavvy** [Tamaized/VoidCraft#130]
The title says it all, but even in Creative and Spectator mode I still die, which I thought it was impossible to die in spectator mode.  I cannot continue completing the achievements and Void Vade Mecum.  This kinda a mod breaking glitch. Perhaps raise the world limit so as to not cause death.

**Comment by Tamaized** [comment]
Intentional, use the Potion of Plenum.

**Comment by SolSavvy** [comment]
Thank you. Couldnt find that in the book to research. So much to read :D

**Comment by Tamaized** [comment]
Ah apparently I did forget to mention in that entry that a potion would be needed... I should add that in. Reopening this till I do so.

**Comment by SolSavvy** [comment]
Is there anyway to learn how to make a potion of plenum? Right now as we speak I am creating throwable potions to unlock possible other recipes for the Voidic Alchemy table

**Comment by Tamaized** [comment]
It can be found in the documentation side of the Vade Mecum, also in JEI if you have that installed, it's crafted with the Voidic Alchemy table. For the documentation side, look in Ethereal Fruit.

**Comment by SolSavvy** [comment]
Used the potion of plenum, got up a Void City tower with an airdock, but still haven't recieved Total Control. Did i maybe misunderstand the text?

**Comment by Tamaized** [comment]
It's possible for some of the towers to glitch out during world gen and not be considered a real structure, if that's the case then you would need to find another one unfortunately. I have no idea what causes that issue and no idea how to fix it but it seems quite rare from my testing. Also, make sure you're at least Y level 187.

**Comment by SolSavvy** [comment]
I thought it might be a height issue so i flew up to Y:386,
still nothing. Here is another tower i found at an Airdock height of Y: 205
![2017-04-12_22 51 25](https://cloud.githubusercontent.com/assets/27328200/24988225/95de8846-1fd2-11e7-80fb-9f45f097e051.png)

**Comment by Tamaized** [comment]
Have you checked your Vade Mecum itself to see if you have the new ability? (Voidic Flight), this specific task actually doesn't announce that you've gotten it other than achievement but you cant rely on seeing the achievement as confirmation.

**Comment by SolSavvy** [comment]
Havent found it in the book or achievement manager.besides the Vade Mecum is still asking me to do this task.

**Comment by Tamaized** [comment]
Quite odd, I did however just test this myself without any issue, could be another broken structure for some reason, very odd though since i'm literally spawning them the exact same way vanilla spawns end cities lol

**Comment by SolSavvy** [comment]
It's probably my world. Might have to delete and try again.

**Comment by Tamaized** [comment]
I suppose I can make it similar to the "Hold a Void Star", basically use the Astral Essence instead as it's only found in these structures.
