### ISSUE TITLE
Add Star Forge effect costs to the Vade Mecum

### ISSUE THREAD

**Issue by Leafygreens97** [Tamaized/VoidCraft#131]
The title explains the gist of what I am saying here, but let me expand on that. Considering how difficult and long all of the boss fights were my first go around (not to mention how many times I died), it would be nice to have a quicker way of getting back to the forge after I've already beaten Xia, since the dimension resets every time you enter it. Sure, his fight will be much easier now that I've unlocked all void infusion powers, but it feels like too much of a process to be forced to fight him and the others again just to get back to the forge after I've collected more materials for it. 

I understand that perhaps you wanted Xia to be the only source of Quori fragments, as the Mecum suggests, but I feel like fighting him again should be optional. Maybe, after you've beaten him for the first time, a portal or teleporter of some sort will generate near the entry point of the dimension that takes you back to the forge.

**Comment by Tamaized** [comment]
Considering how insanely powerful StarForge tools are, that's not going to happen. I intended it to be a giant grind and crazy hard to make these tools and weapons. 

Lore wise when you enter this dimension it's in a specific period of time (yay time travel shenanigans) so there's that :P You also get a new speech from the Twins when you beat Xia for a second time, yay even more lore stuff. More speeches are in the works.

However, the materials themselves are going to be much, much, much easier to get with the addition of a new dimension in the Dream Update so look forward to that.

As always, what I tell everyone about this boss fight, with enough practice it becomes a cake walk. Ethereal fruit are your best friend.

**Comment by Leafygreens97** [comment]
Then perhaps once you have reached the forge for the first time, the Mecum will display the recipes and the materials needed for each tool and upgrade? The main reason I wanted to go back very often at all was to see what I would need to make and upgrade more tools and weapons, and it would be nice to have a quick reference to that. Seeing how each of the upgrades have their own page already, I figure it would fit well to also include their material requirements.
