### ISSUE TITLE
bug grave doesnt drop when fighting xia and you die(1.11.2) even in creative

### ISSUE THREAD

**Issue by SDUBZ** [Tamaized/VoidCraft#135]
voidcraft: VoidCraft-1.11.2-0.18.3
tamazied: TamModized-1.11.2-0.7.1
forge:1.11.2-2282
garve mod: TombManyGraves-1.11.2-3.0.6

![2017-04-24_20 11 19](https://cloud.githubusercontent.com/assets/14084377/25332533/335caa34-292a-11e7-8c83-3c4d2a6f04ca.png)

**Comment by Tamaized** [comment]
Known and I may just keep it considering how hard the place is. For example if you die during any of Xia's forms you're basically locked out anyway until you reach that point again.

Anyway I cancel the block place event and I can't really add an exception for one mod or else I have to account for every single mod of this nature out there and that's a bit much to handle.

On another note if you don't have a graves mod and you die during the first form your stuff can drop into one of the many holes of reality and get destroyed. Death during his second form and all that stuff drops into the void. So not really that big of a deal imo. Just don't bring very important stuff here if you're not confident in surviving.
