### ISSUE TITLE
Config request: Allow for disabling of ore generation (1.10.2)

### ISSUE THREAD

**Issue by Synngularity** [Tamaized/VoidCraft#136]
Sometimes modpack makers wish to customize ore generation using other mods (CoFHCore, others). It would be helpful if VoidCraft's ore generation (Void Crystal Ore, Cosmic Ore, etc.) could be disabled so it could be handled by other mods instead. As far as I can tell there is currently no way to configure VoidCraft to do this. Is this a feature you might be interested in implementing? Thanks for reading!

**Comment by Tamaized** [comment]
CoFH can't disable it? I'm using standard WorldGenMineable

**Comment by Tamaized** [comment]
Ah... looked into it. Seems CoFH can't disable generation. Sure i'll add in a few config options to disable various generations.

**Comment by Synngularity** [comment]
Yeah, as far as I know CoFH only is able to disable vanilla generation. Thanks very much being willing to do this for VoidCraft!

**Comment by Synngularity** [comment]
Just letting you know that this seems to be working perfectly in the newest update. Thanks very much!
