### ISSUE TITLE
[Bug] Void Crystal Blocks Create X-ray Vision

### ISSUE THREAD

**Issue by Leafygreens97** [Tamaized/VoidCraft#137]
I have provided a couple of screenshots if the title isn't descriptive enough.

You may notice non-Voidcraft mods in the bottom screenshot. This is when I first noticed the bug. However, the top screenshot was tested in an instance with only Voidcraft installed, so other mods aren't the issue here. If you're wondering, that yellow thing in the bottom screenshot is the sun.

![2017-04-27_16 05 32](https://cloud.githubusercontent.com/assets/26660001/25506444/f152c09c-2b63-11e7-98e5-3c5239f99ca3.png)

![2017-04-27_10 39 22](https://cloud.githubusercontent.com/assets/26660001/25506455/00818422-2b64-11e7-89da-9ab30d080e04.png)

**Comment by Tamaized** [comment]
Known, I just forgot to override a few methods. This will get fixed whenever I get around to getting another build out. Probably when I update TamModized again.
