### ISSUE TITLE
Void Portals not generating

### ISSUE THREAD

**Issue by ApertureDragon29** [Tamaized/VoidCraft#139]
It seems the void portal no longer generates a portal in the void rather, it teleports you to the exact same coordinates as the block you were on when you got in. a portal in the void seems to teleport you a few blocks off from the block you were on prior to the teleport and also no longer generates an over-world portal.

**Comment by Tamaized** [comment]
knew i shoulda tested the new system a bit more :P will get a fix out soon

**Comment by ApertureDragon29** [comment]
Okay. Glad to help!

**Comment by Tamaized** [comment]
Do you know if the Xia portal has the same issue? When I tested it last night it seemed fine.

**Comment by ApertureDragon29** [comment]
The xia portal seems fine.

**Comment by Tamaized** [comment]
pretty sure I found the issue as to what happened and thankfully the only mod that would need to be updated will be TamModized. Will test it first this time :P

**Comment by ApertureDragon29** [comment]
Okay.
