### ISSUE TITLE
Default Dim

### ISSUE THREAD

**Issue by Kashdeya** [Tamaized/VoidCraft#144]
I was wondering if you could add a config setting/option to make the void a default starting dim. I have tried using the Default World Generator mod but your void world mod does not show up in the list. 

Thank you 
Kashdeya

**Comment by Tamaized** [comment]
That mod allows you to choose the starting dimension? Also, quite curious as to why you would want The Void to be where players begin in. If they're not prepared then Voidic Infusion along with the mobs there will kill them within minutes.

**Comment by Tamaized** [comment]
In any case, I feel it's not this mod's job to determine the dimension players start in when they create a world. That should be left to an entire new mod for such a purpose.

**Comment by Kashdeya** [comment]
That mod lets the modpack makers pick what default world type to lock a pack to a worldtype when making a custom pack. it supports any mod that uses the default world type setting on the menu. this is why I was asking if you would be willing to add support for default world gen mod. so that I can make a modpack based around your dim world. but seeing as you are not even willing to talk or much less hear me out before just shutting me down. I will move onto another dim mod that will work with modpack makers and other devs like myself. 

Thank you and have a wonderful day.
Kashdeya

**Comment by Tamaized** [comment]
My dimension isn't a World Type is the issue and no I have no plans to make it so. You can do a pull request if you'd like if you feel like figuring it out.

**Comment by Tamaized** [comment]
So I actually looked into it, World Types use biomes, my dimension uses a Chunk Provider, meaning this is impossible.

Also on your little note on "not willing to talk or much less hear me out"... please, a closed issues does not mean you cannot comment or that it can't be reopened. I close issues when I feel it doesnt fit the mod or simply cant be done.

And yea, your last statement there, I prefer to not work with devs? come on now that's absurd and just being an asshole now. Thanks.

**Comment by Tamaized** [comment]
Go nuts, theres broken bits such as the ore texture and sky texture that cannot be fixed.

**Comment by Tamaized** [comment]
21b702d120f63153dd09948f766b778df614738f

**Comment by Kashdeya** [comment]
I am sorry if I came across like a asshole. I just felt as if you did not want to hear me out or much less care what I had to say. Seeing that you closed the issue before I even had time to respond to the question you asked, And you made it very clear that it is not your mods job to determine where players start. Most mod devs I deal with never close a issue unless it is either fixed or can not be done. and I felt like you were telling me it can not be done so you closed it. I am sorry I took it wrong. I would not have come to another dev asking for a feature if I did not think it would improve onto the mod. Thank you for taking the time and looking into this and replying back. Once again I am sorry for the way things were handled.

**Comment by Tamaized** [comment]
Thank you, I really do appreciate the response. But yea, now to be a bit more civil about things... My first thoughts were that you wanted players to start in the dimension itself... which to my knowledge is kind of impossible upon world creation, but as I looked more into it and actually figured out exactly what you were asking it became clear what needed to be done. I went out of my way to get the suggestion in though despite all of that but please do keep in mind that many many things wont work as intended due to how WorldTypes work.

**Comment by Kashdeya** [comment]
Thank you for working it in. I know explaining things in text is not my best suite. Hell you should have seen me report bugs and comment on things about 3 years ago. lol.
