### ISSUE TITLE
Void Fire under blast furnace not working?

### ISSUE THREAD

**Issue by kusutari** [Tamaized/VoidCraft#145]
Hi, I can't seem to power the blast furnace. The void power is going in correctly, but no matter what I try I can't get the fire to work with the furnace. I'm using the obsidian filled flask to make the fire UNDER the furnace, but to no avail. Let me know if I'm missing something or if it's a bug. Great mod though!

**Comment by Tamaized** [comment]
Void fire directly underneath, voidic power, and the two dusts must be the infused kind from my mod, coal and iron. This is all correct?

**Comment by Tamaized** [comment]
Seems fine to me.
![2017-05-21_20 29 10](https://cloud.githubusercontent.com/assets/9671313/26291595/3f816490-3e64-11e7-945f-b057fd972969.png)
