### ISSUE TITLE
Option to Disable music in Xia's Dimension

### ISSUE THREAD

**Issue by wheelsfire** [Tamaized/VoidCraft#146]
Hi, I'm working on my own pack which has the `ActualMusic mod in it. Which adds your own music to boss fights, dimensions and biomes. I've tried to include music for the herobrine and Dol and Zol as well. I've also discussed this with the developer of ActualMusic to see if there was a way to disable it without modifying your files. Unfortunately, He couldn't find a way to do so. 

So i was wondering if there's a possibility to include in the config to disable the music in Xia's dimension if possible?

**Comment by Tamaized** [comment]
Yea, the way my music system is setup it cant be disabled by a third party, well without ASM but gl with that (Well AFAIK anyway). Yes I can do a config file for this but it'll be either in a few hours when i've got free time or tomorrow (currently 10pm for me)

**Comment by wheelsfire** [comment]
Awesome thanks! Will be very helpful for modpack makers in the future 👍

**Comment by Fokson** [comment]
Hey, just thought I'd pop in and let you know that I (third party) successfully disabled your music system. =)  
You can save yourself the effort of the config file stuff if you want, though it may still be useful for others not using my mod.

**Comment by Tamaized** [comment]
Nice, i'll still add it in for the sake of it though.
