### ISSUE TITLE
Void Macerator turns Lead Ore into Void Copper Dust

### ISSUE THREAD

**Issue by Xman7373** [Tamaized/VoidCraft#148]
![2017-05-20_15 04 52](https://cloud.githubusercontent.com/assets/28369371/26278652/ee41d6ba-3d6d-11e7-8271-40ddd55ad1ea.png)
![2017-05-20_15 04 54](https://cloud.githubusercontent.com/assets/28369371/26278653/ee41d138-3d6d-11e7-880b-452fbab4d367.png)
As shown in screenshots, Lead Ore (with oredictionary -oreLead) is turned into void copper dust by the void macerator.

**Comment by Tamaized** [comment]
Was this the only oreDict miss-match? All other metals, mainly modded, work correctly?

**Comment by Xman7373** [comment]
Similar issue with aluminum ore upon further testing:
![2017-05-20_15 27 28](https://cloud.githubusercontent.com/assets/28369371/26278787/e9ac2940-3d70-11e7-82fc-db335cf1d284.png)
![2017-05-20_15 27 36](https://cloud.githubusercontent.com/assets/28369371/26278786/e9aa6772-3d70-11e7-8cd8-ca9db745359d.png)

**Comment by Tamaized** [comment]
Right, so it's my entire macerator system thats broken, good to know

**Comment by Xman7373** [comment]
Iron and emeralds work correctly.
