### ISSUE TITLE
Void Macerator not consuming power when processing ores

### ISSUE THREAD

**Issue by Xman7373** [Tamaized/VoidCraft#149]
First image to show that the adjacent voidic power generator is not generating power
![2017-05-20_15 31 18](https://cloud.githubusercontent.com/assets/28369371/26278812/8136edc2-3d71-11e7-8fba-f56fe5435b7e.png)
![2017-05-20_15 31 35](https://cloud.githubusercontent.com/assets/28369371/26278811/813598fa-3d71-11e7-8432-4db11d7a9cd1.png)
![2017-05-20_15 31 42](https://cloud.githubusercontent.com/assets/28369371/26278813/8139b99e-3d71-11e7-927a-c95377cf1084.png)
Note how the power does not decrease before and after processing the iron
![2017-05-20_15 33 02](https://cloud.githubusercontent.com/assets/28369371/26278823/a21ce5f0-3d71-11e7-8902-5944cf005e49.png)
more evidence to this end

**Comment by Tamaized** [comment]
Just to confirm, this is the latest version?

**Comment by Xman7373** [comment]
No, this is 0.18.5. Sorry if this isn't a relevant issue, then

**Comment by Tamaized** [comment]
yup, was fixed in 0.19.1
