### ISSUE TITLE
1.11.2-0.19.6 LordofBlades causes NEAT to crash the client.

### ISSUE THREAD

**Issue by kreezxil** [Tamaized/VoidCraft#154]
I've reported this to Vazkii already, however, since it happens on just this entity which is brought in via spawn egg, I thought you should know.

https://pastebin.com/7HaREqrm

**Comment by kreezxil** [comment]
if this is experimental code, can you do something to block pulling in that entity? maybe add a config that disables them?

**Comment by Tamaized** [comment]
Uhh, why are you spawning g the entity in the first place, it doesn't have any attributes set

**Comment by kreezxil** [comment]
Because we were doing creative testing

**Comment by Tamaized** [comment]
Well it doesn't spawn naturally in the mod nor is it documented anywhere, it's very very unfinished and won't be done for quite some time. Just don't spawn it in I suppose.
