### ISSUE TITLE
[1.11.2] Unable to get Forge Energy into the Heimdall

### ISSUE THREAD

**Issue by GuntherDW** [Tamaized/VoidCraft#169]
According to the UI, cursory look at the code and the MCF page you should be able to, besides just inserting voidic quartz be able to create liquid void for machines.
I am however unable to attach, drain or even recognise anything to drain any FE.

I don't know if Mekanism supports FE. I know it supports Tesla/RF/Mek's own Joules system, but mods like RFTools and TechReborn do support FE.

Blocks (+mods) I tried ->
 - Flux Plug from Flux Networks. Doesn't want to connect to any side, let alone transfer power
 - RFTools Power Cell from RFTools. Set to output but didn't want to transfer any power
 - MFE from TechReborn or cables from said mod. Don't connect or transfer anything.
 - Mekanism cables or Energy Cube. Don't connect to the block.

Items (+mods) I tried ->
 - TechReborn Energy Crystal. Goes into the slot but doesn't get drained or fill up the FE buffer.
 - ActuallyAdditions Battery. Also goes into the slot but doesn't get used.
 - Integrated Dynamics Battery. Same as above.

Versions :
 - Minecraft : 1.11.2
 - Forge : 13.20.0.2315
 - VoidCraft : 1.11.2-0.19.6
 - TamModized : 1.11.2-0.9.2

**Comment by Tamaized** [comment]
Heh, seems my Forge Energy capability is missing, no idea how that happened and not sure how long it's been like this.
