### ISSUE TITLE
Disabling ore gen doesn't prevent generation

### ISSUE THREAD

**Issue by Synngularity** [Tamaized/VoidCraft#171]
About two months ago you provided config options to disable Cosmic Material and Void Crystal Ore from generating in the end. This was great since I could then use CoFHCore to customize ore gen. It worked in VoidCraft-1.10.2-0.18.4.jar, but at some point between VoidCraft-1.10.2-0.18.5.jar and VoidCraft-1.10.2-0.19.6.jar it stopped working. The config options are still there, they just don't actually disable ore gen. Is there any chance you can look into this? Thanks Tamaized!

**Comment by Tamaized** [comment]
Will look into it but do know all further updates are going into the 1.12 versions.

**Comment by Tamaized** [comment]
I have no idea how but it got fixed during this commit
35b070a2e65d2c6b139c04fa93ced0ce4b5aa588
