### ISSUE TITLE
Startup crash [1.12]

### ISSUE THREAD

**Issue by NoplixDE** [Tamaized/VoidCraft#174]
Everything is updated, I don't know what causes it. If I go one version back with Voidcraft everything works great.

Error Log:
https://gist.github.com/NoplixDE/9ec5a2174aec4fb87cb6d854b345b504

**Comment by Tamaized** [comment]
Okay that's really weird, looks like my grade build failed really bad

**Comment by NoplixDE** [comment]
#hyperfastresponse xD 
I guess a hot fix will come?

**Comment by Tamaized** [comment]
Yea, would have to be sometime later today though as its currently 2am for me, I'll mark that build as alpha or something at least
