### ISSUE TITLE
Xia generation problems

### ISSUE THREAD

**Issue by ApertureDragon29** [Tamaized/VoidCraft#176]
In the most recent version of voidcraft (1.12-0.22.1) the Xia dimension doesn't generate right. none of the voidbrick blocks generate, nor do most of the holes in reality and the voidcraft:blocknobreak. I've tried in three different worlds (two of which were only voidcraft and TamModized

**Comment by Tamaized** [comment]
sounds like my teleport code got messed up somehow, looking into it now

**Comment by ApertureDragon29** [comment]
Okay. Thanks!

**Comment by Tamaized** [comment]
okay nevermind it's not the teleporter >.> I forgot to fix the NBT values after I changed my registry

**Comment by ApertureDragon29** [comment]
Oh.
