### ISSUE TITLE
MC 1.11.2 Compatibility issue w/ SimplyHax flying

### ISSUE THREAD

**Issue by blackviperr** [Tamaized/VoidCraft#177]
I've been debating for a few months whether to post this or not and am not sure if it is fixed, but when I play mc 1.11.2 with both voidcraft and simplyhax (allows you to fly in survival & sprint faster) I can no longer fly, I just fly-jump (can't stay flying.) will post this in Simplyhax github also. 

Thank you for your time and I love this mod xo

**Comment by Tamaized** [comment]
Does SimplyHax have issues with other mods that adds flight? My checks are exactly the same as Botania's. Might be a good idea to check if it works along side botania and if not i'd say it's on their end.

**Comment by blackviperr** [comment]
I'm not quite sure. Will do. thank you xo
