### ISSUE TITLE
1.12 Server crashes on startup.

### ISSUE THREAD

**Issue by NoplixDE** [Tamaized/VoidCraft#181]
I guess you forgot just something simple to add xD

https://gist.github.com/NoplixDE/ec0fc63b4a3b668bce4e60aaccb551b7

**Comment by NoplixDE** [comment]
I don't wanna stress but will there be a fix today or not because I have to plant stuff with my modpack release otherwise.

**Comment by NoplixDE** [comment]
Sry idk why I did that I thought it only comment it xD! "miss clicked" :/

**Comment by Tamaized** [comment]
Yes, It'll be a bit later, it's 8:30am and I just woke up :P

**Comment by NoplixDE** [comment]
Oh yea different time zone haha for me it's 6 pm :P
