### ISSUE TITLE
Crashes when Clicking on Recipe Book

### ISSUE THREAD

**Issue by NoplixDE** [Tamaized/VoidCraft#182]
Looks like some or one recipes crashes the game from your mod.

Crash: https://gist.github.com/NoplixDE/f136292e492698e91f1be8585966e83e

**Comment by Tamaized** [comment]
Okay so, I have no idea what's causing this nor can I even reproduce it.

**Comment by NoplixDE** [comment]
Okey then it's an other mod. I will look into it and test stuff. Thanks for the info.

**Comment by Tamaized** [comment]
After talking with others, this is due to some weird stuff another mod is doing, nothing to do with mine.
