### ISSUE TITLE
Voidcraft+Mo'Bends: Distorted player

### ISSUE THREAD

**Issue by CleverCreations** [Tamaized/VoidCraft#183]
I'm not sure if you accept bug reports where your mod breaks other mods, but when using Mo Bends and Voidcraft, the player seems to become distorted/pulled apart. The only fix is to hold something in your right hand, but as soon as you put the item away, you become broken again. Is there a fix for this, or do I have no choice but to remove one of the mods?

![screenshot 13](https://user-images.githubusercontent.com/30176275/28210495-b212a368-6865-11e7-9248-fc933d282f73.png)
*Distorted player*
![screenshot 14](https://user-images.githubusercontent.com/30176275/28210515-c62e4f14-6865-11e7-9e45-a7783abf3131.png)
*Fixed while holding an item*

**Comment by Tamaized** [comment]
Looking through his issue tracker this exact distortion happens with multiple mods. His mod isn't open source as far as I can tell so I can't see what's causing this exactly. I doubt it's my end really.
