### ISSUE TITLE
SP crash / MP disconnect when using Voidcraft Macerator

### ISSUE THREAD

**Issue by davqvist** [Tamaized/VoidCraft#184]
Might be mod incompability with LimeLib from MrRiegel

See https://github.com/MrRiegel/LimeLib/issues/6

Voidcraft 0.23.2

**Comment by Tamaized** [comment]
Does this happen with any other machines of my mod or just the macerator?

**Comment by davqvist** [comment]
Not tested yet as the world is kinda corrupted when placing the Macerator down, but I will do some tests.

**Comment by Tamaized** [comment]
I have a sneaking suspicion that this is due to cofh again, my machines don't provide any power cap for other mods besides Heimdall. Will do some if my own tests here in a bit.

**Comment by davqvist** [comment]
Placed Blast Furnace, crashed my game as well, same error message. That was in SP, not going to test in MP.

**Comment by MrRiegel** [comment]
the problem is that `hasCapability()` returns true but `getCapability()` returns null. that's invalid.
why should that be a problem with cofh?

**Comment by Tamaized** [comment]
That shouldn't be possible from my end. If my ItemStackHandler is null then I return the super of hasCap and getCap. As that's the only cap on these machines from me.

**Comment by Tamaized** [comment]
Most likely because i'm not actually checking for `ITEM_HANDLER_CAPABILITY` on hasCap, I must of been drunk when I wrote that ¯\_(ツ)_/¯

Fixing it now

**Comment by MrRiegel** [comment]
yeah, once I forgot checking for capability as well.
ok, I close my issue
