### ISSUE TITLE
Opening Void Vade Mecum does nothing

### ISSUE THREAD

**Issue by davqvist** [Tamaized/VoidCraft#185]
I just upgraded to 0.24.1 and now opening the Void Vade Mecum freezes the screen, like an empty GUI.
You have to press ESC to be able to do something again. As this didn't happen before something from the update must have broken it.

MC 1.12
Forge 2420
Voidcraft 0.24.1

**Comment by Tamaized** [comment]
Was this on a dedicated server or single player?

**Comment by Tamaized** [comment]
Ah nvm, I see what happened. Some test code slipped by me that I totally forgot to revert.
