### ISSUE TITLE
Server crash when creating Xia portal

### ISSUE THREAD

**Issue by davqvist** [Tamaized/VoidCraft#188]
MC 1.12
Forge 2443
Voidcraft 0.24.2

A player made the portal into the dimension were xia is. It crashed the server, and whenever he logs on, it crashes the server again.

https://pastebin.com/jpYW4Cjw

**Comment by davqvist** [comment]
Thanks for the quick fix, one character can make a big difference :P

**Comment by Tamaized** [comment]
Yep hehe
