### ISSUE TITLE
Xia Portal Won't Open

### ISSUE THREAD

**Issue by Plurp13** [Tamaized/VoidCraft#190]
Maybe I'm unclear on what I'm supposed to do exactly but the instructions seem fairly straight forward. I tried throwing a void star into a hole of soft bedrock and then I tried throwing the void star and then placing soft bedrock around it, neither seems to have worked. I tried completely enclosing the star in soft bedrock and waited a little while but still nothing happened. Am I doing something wrong or is this some kind of bug?

**Comment by Tamaized** [comment]
It should be a 3x2x3 of soft bedrock where the top layer should be empty in the center, that's where you throw the star

**Comment by Plurp13** [comment]
2 high huh? Just tried that too, still nothing, here's a picture, you can see the star just spinning around down there. I know it's still entirely possible I'm just misunderstanding.
![2017-08-22_18 30 33](https://user-images.githubusercontent.com/8428847/29590539-53ddd5b6-8768-11e7-9045-aaf4270630a0.png)

**Comment by Tamaized** [comment]
I'll check it out incase something broke

**Comment by Plurp13** [comment]
Oh I should probably have mentioned this is 1.11, and I just remembered you're not supporting that anymore so never mind. Thanks for replying so quick though, my mistake. ^.^

**Comment by Tamaized** [comment]
Ah yea, possible it's broken in that version, I can't remember. However this is what it should look like and does work in the current versions just fine.
![2017-08-22_15 38 16](https://user-images.githubusercontent.com/9671313/29590723-0e0f384e-8750-11e7-8921-256a77b43921.png)
