### ISSUE TITLE
[1.12.1] Crash Duplicate stat id

### ISSUE THREAD

**Issue by MokahTGS** [Tamaized/VoidCraft#196]
Getting a crash with 1.12.1:  https://pastebin.com/ZRqBpJqb

Just added Animania and Mo Creatures both of which were just updated to 1.12.1  Not sure if there is a correlation, but that is the major change since last run of this instance.

**Comment by MokahTGS** [comment]
So I confirmed it has something to do with either MoCreatures or Custom Mob Spawner.  Everything seems to be working fine with Animania.

**Comment by Tamaized** [comment]
It can be fixed on my end, i'm pretty sure anyway. I just need to add my modid to my unlocalized names. (It should have been there from the start but whatever)
