### ISSUE TITLE
BUG- Can't Open Spells Tab

### ISSUE THREAD

**Issue by gwest314** [Tamaized/VoidCraft#204]
What happened was I opened up my spells, selected the flame spell, or whichever uses flint, then closed the book and tried to cast the spell. The spell didn't cast and I could not reopen the spells tab from then on. Restarting my client or the server does not fix the problem. Playing on version 1.10.2, forge version 12.18.3.2511

**Comment by Tamaized** [comment]
1.10.2 isn't supported
