### ISSUE TITLE
Neptune Staff Freezing Crash

### ISSUE THREAD

**Issue by mkozuma** [Tamaized/VoidCraft#206]
When I try to freeze a mob, my minecraft crashes with the following error message, "The game crashed whilst rendering entity in world
Error: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: layerRenderers." I am doing this in a superflat world using the following other mods: Advanced Swords, Biomes o Plenty (not in a BOP world though), Grim Pack, Just Enough Items, More Commands, OptiFine HD, and of course Tam Modized. Is this a common issue with 1.12.2 or is this just with my Minecraft?

**Comment by Tamaized** [comment]
I have no idea what a Neptune Staff is, def not from my mod, show the log

**Comment by mkozuma** [comment]
I apologize this is from the grimpack mod thank your for the quick response. Sorry about the inconvenience.
