### ISSUE TITLE
[BUG] Minecraft Shield not taking durability damage

### ISSUE THREAD

**Issue by dewobedil** [Tamaized/VoidCraft#208]
**Forge Version: 14.23.0.2503
Minecraft Version: 1.12.2
Launcher: TechnicLauncher
VoidCraft Version: VoidCraft-1.12.1-0.26.7.jar
TamModized Version: TamModized-1.12.1-0.15.3.jar**

**Error Console: no error**

Step:
1. Wear shield
2. Hold right click to defend
3. Shield not taking damage or not having knockback animation
4. End

**Comment by Tamaized** [comment]
I can't reproduce this, it seems to be working fine.

**Comment by dewobedil** [comment]
I'm not sure why, you can look at this video i just record
forge version and plugins version in the video
https://youtu.be/N9FrMud3pnA

**Comment by Tamaized** [comment]
Most likely a mod conflict, can you narrow down which mod is causing this. Does it happen in singleplayer?
