### ISSUE TITLE
[BUG] Does not work in multiplayer LAN.

### ISSUE THREAD

**Issue by DesolateElf** [Tamaized/VoidCraft#209]
When I try to connect to a LAN world with VoidCraft installed, the game presents me with this message:

Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine

**Comment by InsomniaKitten** [comment]
Please upload your game log to gist or pastebin and post the link here

**Comment by Tamaized** [comment]
^ need the log

**Comment by DesolateElf** [comment]
[latest.log](https://github.com/Tamaized/VoidCraft/files/1487351/latest.log)

**Comment by Tamaized** [comment]
I need fml-client-latest.log right when the error happens as the file gets wiped when you relaunch. Also on the log you just posted is nothing but a gl state leak error that has nothing to do with the error you describe

**Comment by DesolateElf** [comment]
Thanks, I solved the problem, I just installed Forge 14.23.0.2528 and entered the game normally
