### ISSUE TITLE
1.10.2 uses hardcoded dimension ids

### ISSUE THREAD

**Issue by LemADEC** [Tamaized/VoidCraft#215]
As of VoidCraft-1.10.2-0.19.6, the configuration for dimension ids has no effect.
As of VoidCraft-1.12-0.26.9, issue isn't reproduced.

**Comment by Tamaized** [comment]
1.10.2 isnt supported

**Comment by LemADEC** [comment]
yes, it's just a reminder for whoever wants to use 1.10.2.
