### ISSUE TITLE
[1.11.2] Hole In Reality No Longer Teleports Player

### ISSUE THREAD

**Issue by Leafygreens97** [Tamaized/VoidCraft#216]
I don't know if you're still supporting the 1.11.2 version, but I figured I would post this issue anyway. The title says all there is to know really. It removes non-player entities as usual, but the player just falls through it and gets pushed out if able, as is normal for being stuck in blocks.

On an unrelated note, is there someplace I can look where you post updates on this mod? I know you don't use the Minecraft Forum post anymore, and I don't know where to look besides here.

**Comment by Tamaized** [comment]
No, 1.11 is no longer supported, just 1.12 for now.

As for updates, I havent had much time to work on anything modding related and VoidCraft especially hasnt gotten any attention at all in months.
