### ISSUE TITLE
Crash With Herobrine

### ISSUE THREAD

**Issue by Anromora** [Tamaized/VoidCraft#23]
https://gist.github.com/Anromora/ecaf05b9eda3df6cf970ea1122206ea5

**Comment by Tamaized** [comment]
Seems Skin Handler has an issue aswell here, could be related to forge version

**Comment by Anromora** [comment]
<script src="https://gist.github.com/Anromora/002fd476ef6815ba9306e31921bd291b.js"></script>

**Comment by Tamaized** [comment]
Confirmed to be fix
