### ISSUE TITLE
Source must not be null

### ISSUE THREAD

**Issue by jsaggers** [Tamaized/VoidCraft#33]
Mod is looking amazing.
Getting a crash with my personal pack that states Source must not be null error.
Crash report attached. I created an instance just with your mod and the required library and i still got the error.
[crash-2016-10-03_20.44.07-client.txt](https://github.com/Tamaized/VoidCraft/files/505931/crash-2016-10-03_20.44.07-client.txt)
Seems like another person posted this issue the same time I did :)

**Comment by Tamaized** [comment]
Is this also with a non-vanilla client? such as the curse client.

**Comment by Tamaized** [comment]
fixed alongside #32 
if this issue persists in build 0.9.3+ feel free to reopen this
