### ISSUE TITLE
Can you add this?

### ISSUE THREAD

**Issue by Kevadro** [Tamaized/VoidCraft#34]
When you fell to the vanilla void, (if you survive enought) you be teleported to the void dimension. Example: if you get to -1000 blocks or lower, you be teleported to the void dimension
Add void elytras that acts like void armor (protects you from the void).
Example: when you fall to the void, you spawn in 255< blocks, whit the elytras, you can survive from that fall.

Im not sure if any of these features are implemented, I don´t played the mod yet.

**Comment by Tamaized** [comment]
The falling at a certain Y level to enter the void is implemented already though not recommended and I don't plan to prevent actual void damage though that could be a thing in the future.

**Comment by Kevadro** [comment]
You can enter to the void in the end/nether?

**Comment by Tamaized** [comment]
Yes

**Comment by Tamaized** [comment]
Thinking back on it, The Elytra idea could be a good one, I might actually add that bit in

**Comment by Kevadro** [comment]
A last question:
can you make a chestplate with an extra model and animation from the elytra for more protection to the void (like mix elytra with an armor) (like an armor with elytra functions)

**Comment by Tamaized** [comment]
Yep I can

**Comment by Kevadro** [comment]
:) good.

**Comment by Tamaized** [comment]
I've been looking through the vanilla code trying at my own Elytra for the past 2 days but it's too hardcoded and not really possible as far as I can tell. Without ASM anyway but I refuse to use ASM. If I ever find a way to implement this, I'll do so asap.

**Comment by Kevadro** [comment]
Now, I understand why aren´t any mods that add elytras...
