### ISSUE TITLE
Void Vade Mecum

### ISSUE THREAD

**Issue by Tamaized** [Tamaized/VoidCraft#37]
Current TODO List:
- [x] Redo and Proofread Vade Mecum entries
- [x] Documentation as well as an Entry to describe the current gained Voidic Infusion control abilities.
- [x] Achievements
- [x] Potion Icons
- [x] Throwable Potions

**Comment by Anromora** [comment]
I'll look over the documentation on our Minecraft Forum post and build upon it at a later date.

**Comment by Tamaized** [comment]
We need a proper name for this book, Book of Lore is too Aether like

**Comment by Anromora** [comment]
I'll work on the name and the book's contents today. I'm considering having multiple versions as well, one for each of the original team members.

Yours can be a wiki-like manual, mine can be more like a narrative (while still providing basic how-to's), and TheRottingLink's can be an almost destroyed book, save for some of his greatest one liners.

**Comment by Tamaized** [comment]
Single book only and I have a few plans along side it aswell. Keep it to documentation right now.

**Comment by Anromora** [comment]
K lol

**Comment by Tamaized** [comment]
Ok so what I had in mind for this is that on the main page of the book there's two options, the full documentation and the second option is what i'm about to get into:
- This will be some sort of progression system in the mod
- You feed the book with items from the mod to progress
- Each time an item is fed into the book it'll basically examine it and give you full details about the item and what can be done
- I'd like to implement some sort of powers that get unlocked eventually
 - Words of Power is what I was thinking and how they work would be you set a currently unlocked word as active for the book and upon a keybind of some sort of shift right click with the book the power activates.
 - The powers can be regenerated somehow that still needs to be figured out
 - an example of a power would be setting the amount of voidic infusion you have and it will not increase or decrease under any situation
- Another category of power that could be unlocked is what exactly voidic infusion does to you

This is all I have right now as I literally came up with the ideas last night

**Comment by Tamaized** [comment]
Full documentation part (Probably wont be fully finished) will be in 0.9.6.
The magic based part will be in 0.9.7

**Comment by Tamaized** [comment]
To obtain the book.. I'm thinking toss an Obsidian Flask onto the ground to create voidic fire. Toss a vanilla book into the fire and it'll cause an explosion, non-world damaging. Fire and old book will be gone. In their place is the Void Vade Mecum. This allows for the Vade Mecum to be obtained early game before reaching The End.

**Comment by Anromora** [comment]
Return to the home page/index by clicking on the left side of the Book's Inner Cover while in an entry.

Proceed to Mod Credits, Build Information, Patreon or Contributor Perks by clicking on the right side of the Book's Inner Cover while in any part of the book.

**Comment by Tamaized** [comment]
Documentation base line finished, bumping this to 0.9.7 for the magic/progression bit

**Comment by Tamaized** [comment]
Progression system advances through a Ritual system, this will be the generic consume items but in a less bland way. You place down blocks like a multiblock then right click a Ritual Block within the multiblock with the Vade Mecum in hand. Still kind of dull and needs improvement in design. I do not want a quest system where the player is given very specific tasks like achievements and I don't want something similar to Thaumcraft's Research minigames.

**Comment by Tamaized** [comment]
I'm rethinking the quest system approach, instead of specific tasks we turn this into an exploration type deal, such as something unlocks the first time you enter the void and such after obtaining the vade mecum. This can all be tied to achievements. This would fit the mod style nicely.

I'm keeping the ritual system as well.
