### ISSUE TITLE
Representing the other dimensions' mobs in the Void Fortress

### ISSUE THREAD

**Issue by Anromora** [Tamaized/VoidCraft#39]
As of right now, the only mob present in the Void Fortress is the Void Wraiths (which are buffed versions of wither skulls). Add Shulkers from the End City to remedy this issue.

More ideas are welcome.

**Comment by Tamaized** [comment]
You mean Wither Skeletons ;)
Anywho somewhat true but they don't give wither on hit

**Comment by Tamaized** [comment]
I should totally add the Herobrine Creeper to the Fortress, i'll get a screenshot of them as they're already implemented in the mod. They have boosted effects of a normal creeper but don't do damage to the world.

**Comment by Tamaized** [comment]
![2016-10-03_16 45 46](https://cloud.githubusercontent.com/assets/9671313/19057998/ec6dab82-8988-11e6-8364-e9d07556a6e9.png)
