### ISSUE TITLE
Point and Click Teleportation using Holes in Reality

### ISSUE THREAD

**Issue by Anromora** [Tamaized/VoidCraft#44]
Interdimensional Transport, Pocket Dimensions, Point and Click Teleportation.

**Comment by Tamaized** [comment]
Pocket Dimensions?

**Comment by Anromora** [comment]
Remember the Space you made floating above the Void using another Mod? Something like that, but have it be less of a pain in the ass to make a dimension.

**Comment by Tamaized** [comment]
that'll be a pain in the ass

**Comment by Anromora** [comment]
Okay, so forget the Pocket Dimension Part. But Teleporters and "Right Click" teleporting would be cool.

**Comment by Anromora** [comment]
Add a "Dimension Whitelist" to the Void's Config to determine where the Holes In Reality send you when touched

**Comment by Tamaized** [comment]
@Anromora That's #48

**Comment by Tamaized** [comment]
Changing this to just be for the Point and Click function, making a new issue for the teleportation blocks
