### ISSUE TITLE
Should Lich spawn in overworld?

### ISSUE THREAD

**Issue by mrtopf** [Tamaized/VoidCraft#49]
Just a question: I had a Lich spawn in the overworld (next to my bed on day 1). Is this supposed to happen or is this a bug?

**Comment by Tamaized** [comment]
They spawn in swamplands

**Comment by Tamaized** [comment]
The spawn rate is low so for one to spawn near your bed on day one, that's some luck

**Comment by mrtopf** [comment]
Yeah, I just found the list on the forum post, was mostly looking at curse. So that explains it. 
Yeah, wasn't the nicest night ;-) 

Thanks for the explanation!
