### ISSUE TITLE
Redo Entity Models

### ISSUE THREAD

**Issue by Tamaized** [Tamaized/VoidCraft#50]
- [x] Wraith
- [x] Chained Specter
- [x] Lich

Some Notes:
- Wraith model may stay, just needs some arm movements.
- Chained Spectre and Lich models are beyond ugly to me, these need to change.

**Comment by DV666** [comment]
Sorry for the intrusion but entity models still missing i suppose ?

[http://img11.hostingpics.net/pics/60013420170219232541.png](url)

Thanks in advance for further answer :)

**Comment by Tamaized** [comment]
oh god damn it, this is the 1.10.2 version isnt it? I thought I caught all the resource location case issues but looks like i missed these.

**Comment by DV666** [comment]
Yes exactly, it's the version 1.10.2 ^^ I try your mod at this moment for my futur modpack :p

**Comment by Tamaized** [comment]
Alrighty, I'll get a fix out for this in a little bit. Moving this over to #89 as this is a different issue than the issue we're in now.

**Comment by DV666** [comment]
Nice, glad to report you a bug ^^ I will wait your fix and inform you on another post if it will good or not ;)
