### ISSUE TITLE
Give portal a platform?

### ISSUE THREAD

**Issue by mrtopf** [Tamaized/VoidCraft#55]
When I was going through the portal it ended up on the edge of a platform. because of the portal block texture I couldn't really see much and was falling down directly. Without flight that might have been bad. 

So maybe it would be good to create a little platform below the portal? Or at least make the portal blocks themselves a bit translucent so you can see your surroundings.

**Comment by Tamaized** [comment]
I really should. I actually set the player's location one block out of the portal so it's even more of a risk lol. yea i'll do something about it.

**Comment by mrtopf** [comment]
I checked again and in fact I directly fall down.
