### ISSUE TITLE
Empty string not allowed Crash

### ISSUE THREAD

**Issue by jsaggers** [Tamaized/VoidCraft#58]
Voidcraft 0.9.9 with forge 12.18.2.2113 and TamModized version 0.2.4
Crash report  [crash-2016-10-28_11.47.12-server.txt](https://github.com/Tamaized/VoidCraft/files/557379/crash-2016-10-28_11.47.12-server.txt)
I tried going back a few versions of forge and tried deleting the voidcraft config file with no luck.

**Comment by Tamaized** [comment]
I take it this was a new world or first time obtaining the Vade Mecum for the player on the world?

**Comment by Tamaized** [comment]
I'm getting a new build out with the fix, I cant really test it right now but if it occurs again in 0.9.10 go ahead and reopen this.
