### ISSUE TITLE
Crash with Dynamic Surroundings

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Tamaized/VoidCraft#59]
https://gist.github.com/Shadows-of-Fire/838861e88ffd42dae44c590ccddebcec
Not sure whose end this crash is on, but it happened.  Cross-reported to DSurround at https://minecraft.curseforge.com/projects/dynamic-surroundings-unofficial/issues/7

**Comment by Tamaized** [comment]
most likely my end im looking into it though don't expect a build for quite some time, im on very limited time and theres a large project for the mod in the works atm

**Comment by Tamaized** [comment]
It's indeed my end
