### ISSUE TITLE
Tamaized Voidcraft events DamageEvent Crash

### ISSUE THREAD

**Issue by jsaggers** [Tamaized/VoidCraft#61]
Just hit a pig with my sword and crash with the following crash report.
[crash-2016-11-01_11.05.01-client.txt](https://github.com/Tamaized/VoidCraft/files/563092/crash-2016-11-01_11.05.01-client.txt)

**Comment by Tamaized** [comment]
ah shit I thought i put a check for that there guess I missed it.
