### ISSUE TITLE
StarForge Effects

### ISSUE THREAD

**Issue by Tamaized** [Tamaized/VoidCraft#76]
Effects that can be Added to StarForge Weps/Tools
(More to be added, or removed)

These will come in Tiers, 1 through 3. Only one effect per Tier can be applied. No Overwrites.

----
Blank Tools/Swords are crafted with:
  - Cosmic Material: 4
  - Quori Fragment: 1
---
 - Swords:
   - Tier 1
     - [x] Blinding Fear
       - Blinds target on hit
       - Cosmic Material (8), Astral Essence (4), Voidic Phlogiston (4)
     - [x] 1st Degree Burns
       - Sets targets on fire
       - Cosmic Material (8), Voidic Phlogiston (8)
     - [x] Touch of Void
       - Adds 600 Voidic Infusion to target on hit
       - Cosmic Material (8), Astral Essence (8)
   - Tier 2
     - [x] Xia's Blessing
       - Upon striking an enemy, 20% chance to heal yourself for 5 hearts.
       - Cosmic Material (16), Astral Essence (8), Voidic Phlogiston (8)
     - [x] 2nd Degree Burns
       - Adds massive slowness to targets per hit
       - Cosmic Material (16), Voidic Phlogiston (16)
     - [x] Wrath of Void
       - Deal an extra 5 Voidic Damage to targets per hit
       - Cosmic Material (16), Astral Essence (8), Voidic Dragon Scales (8)
   - Tier 3
     - [x] Mortal Fear
       - 20% chance per hit to cut target's current health in half.
       - Cosmic Material (32), Quori Fragment (1), Astral Essence (16), Voidic Dragon Scales (16)
     - [x] 3rd Degree Burns
       - Deal 10 hearts of fire damage per hit
       - Cosmic Material (32), Quori Fragment (1), Voidic Phlogiston (32)
     - [x] Crippling Void
       - 20% chance per hit to set the target's Voidic Infusion to near maximum.
       - This effect also allows the weapon to bypass Incorporeality from Voidic Infusion
       - Cosmic Material (32), Quori Fragment (1), Astral Essence (8), Voidic Dragon Scales (24)
     - [x] Vorpal
       - 5% chance per hit to instantly kill a mob and drop their Head. This only applies to mobs that can drop a Head.
       - Cosmic Material (32), Quori Fragment (1), Astral Essence (32)
 - Tools:
   - Tier 1
     - [x] Haste
       - Cosmic Material (8), Astral Essence (8)
   - Tier 2
     - [x] Silk Touch
       - Cosmic Material (16), Astral Essence (8), Voidic Phlogiston (4), Voidic Dragon Scales (4)
     - [x] Fortune 5
       - Cosmic Material (16), Astral Essence (8), Voidic Dragon Scales (8)
   - Tier 3
     - [x] 3x3 Mining
       - Cosmic Material (32), Quori Fragment (1), Astral Essence (16), Voidic Phlogiston (8), Voidic Dragon Scales (8)

**Comment by Anromora** [comment]
Tool and Weapon Right Click Functions:
Sword: Shoots a Beam of Energy in a straight line. Hold right click for more damage and distance.
Pickaxe: Throw the tool at a block or mob, then teleport to the location the item it hits.
Axe: Slam Axe into the Ground for a damaging AoE effect with massive knockback centered on the player.
Shovel: Place dirt in your inventory in any air block.
Sickle: Tear a hole in reality in the space in front of the player. This summons friendly void creatures to aid the player in battle.

**Comment by Tamaized** [comment]
Tool effects will be for every tool not single tools.

**Comment by Tamaized** [comment]
Include the tiers which these effects should be in aswell.
