### ISSUE TITLE
Throwable Magical potions

### ISSUE THREAD

**Issue by Tamaized** [Tamaized/VoidCraft#79]
Would require Vade Mecum knowledge to craft and would be crafted from the Voidic Alchemy Table. They would be elemental based such as on impact one creates acid and such.

**Comment by Anromora** [comment]
Fire:
Ghast Tear
Nether Wart
Blaze Powder
Magma Cream
Void Fruit
Obsidian Flask

Frost:
Packed Ice
Snow Block
Ectoplasm 
Void Crystal 
Void Fruit
Obsidian Flask

Shock:
Sugar
Glistening Melon
Redstone Block
Glowstone 
Void Fruit 
Obsidian Flask

Acid:
Pufferfish
Slime Block
Fermented Spider Eye
Poisonous Potato 
Void Fruit
Obsidian Flask

Void:
Void Crystal Block
Ectoplasm 
Void Cloth
Void Chain
Void Fruit 
Obsidian Flask

**Comment by Tamaized** [comment]
Taking from Above ^
(All recipes require the normal Ethereal Fruit and Obsidian Flask along with some form of their own research via ritual)
 - Fire Spread:
     - Research Requires Word: Flame
     - Upon impact it causes nearby blocks, at random, to be lit on fire.
     - Crafting: 
         - Nether Wart
         - Blaze Powder
         - Magma Cream
         - Fire Charge
         - Obsidian Flask
         - Ethereal Fruit
 - Freeze:
     - Research Requires Word: Freeze
     - Upon impact it causes nearby entities are inflicted with a 10 second Slowness 5
     - Crafting: 
         - Ice Block
         - Snow Block
         - Ectoplasm
         - Void Crystal
         - Obsidian Flask
         - Ethereal Fruit
 - Lifting:
     - Research Requires Word: Shock
     - Upon impact, all nearby entities are thrown up into the air
     - Crafting: 
         - Glowstone
         - End Stone
         - End Rod
         - Feather
         - Obsidian Flask
         - Ethereal Fruit
 - Acid:
     - Research Requires Word: Acid Spray
     - Upon impact, liquid acid is spawned on top the block impacted
     - Crafting: 
         - Pufferfish
         - Slime Block
         - Fermented Spider Eye
         - Poisonous Potato
         - Obsidian Flask
         - Ethereal Fruit
 - Acid:
     - Research Requires Word: Implosion
     - Upon impact, all nearby entities are inflicted with Implosion
     - Crafting: 
         - Void Crystal Block
         - Hole in Reality
         - Void Cloth
         - Astral Essence
         - Obsidian Flask
         - Ethereal Fruit
