### ISSUE TITLE
was mining and it crashed me(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [Tamaized/VoidCraft#81]
crash report:
[crash-2017-01-19_23.22.12-server.txt](https://github.com/Tamaized/VoidCraft/files/716549/crash-2017-01-19_23.22.12-server.txt)
forge:1.11.2-2222
voidcraft:1.11.2-0.13.2

**Comment by Tamaized** [comment]
Can I see your fml-client-latest.log file after the crash occurs? The file will get wiped if you rerun Minecraft so I need it right when you crash.

**Comment by SDUBZ** [comment]
[fml-client-latest (3).txt](https://github.com/Tamaized/VoidCraft/files/716739/fml-client-latest.3.txt)
here you go havent launched since i crashed

**Comment by Tamaized** [comment]
As I thought, it crashed right when Aroma started its backup process. I'll see if I can fix this.

**Comment by Tamaized** [comment]
Try it with [0.13.3](https://minecraft.curseforge.com/projects/voidcraft/files/2370470)

**Comment by SDUBZ** [comment]
umm you forgot to update the core on curseforge http://puu.sh/trXUP/2ab7cd723d.png

**Comment by Tamaized** [comment]
Yea I just realized that about 10mins ago lol, its being reviewed by curse atm and should be up soon.

**Comment by SDUBZ** [comment]
ok thanks :D

**Comment by Tamaized** [comment]
**_Finally_** done...
[v0.5.2](https://minecraft.curseforge.com/projects/tammodized/files/2370563)

**Comment by SDUBZ** [comment]
[crash-2017-01-20_05.54.08-client.txt](https://github.com/Tamaized/VoidCraft/files/717497/crash-2017-01-20_05.54.08-client.txt)
umm you did a thing

**Comment by Tamaized** [comment]
Quite odd, even tested before I uploaded. Glad there's others to test this for me :P .. working on it

**Comment by Tamaized** [comment]
Ah, looks like I need to update the forge version im using, things have changed and is causing issues.

**Comment by SDUBZ** [comment]
well when i see a improvement on forge i usually update

**Comment by SDUBZ** [comment]
out of curiosity what version were you on?

**Comment by Tamaized** [comment]
13.20.0.2201
I hardly update as it's a slow process in fact my system is locked up and frozen waiting for it to finish lol, but better late than never

**Comment by SDUBZ** [comment]
well thats bad to hear im sorry but it will help in future atleast i hope

**Comment by Tamaized** [comment]
Yep it would, I'm just hoping TamModized will function just fine without updating, looking some stuff over I'm pretty sure it'll be fine so just voidcraft needs the update.

**Comment by SDUBZ** [comment]
wouldnt that conflicts between mod and the core if on different versions?

**Comment by Tamaized** [comment]
Only if the change in the version affects both mods code wise. The issue here is something with registering entities which TamModized doesn't do so it wouldn't crash. Just VoidCraft.

**Comment by SDUBZ** [comment]
well thats good to hear then dont know much about coding so i thought id ask :D

**Comment by Tamaized** [comment]
Alrighty, all fixed and such. Getting another build out and pushing it to curse, all that's left is waiting for it to be approved (Which may take up to another half an hour sadly, or if we're lucky it'll be instant. Kinda out of my control.)

**Comment by SDUBZ** [comment]
yeah as modpack dev i feel for pain for approval times one tim e it took upto 4 hrs once :/

**Comment by Tamaized** [comment]
Good lord that took twice as long as usual..
But here it is: [v0.13.4](https://minecraft.curseforge.com/projects/voidcraft/files/2370600)

**Comment by SDUBZ** [comment]
yeah it got passed loading now to see if it crashes when mining

**Comment by SDUBZ** [comment]
so far no crash i will let you know if anything happens :D

**Comment by Tamaized** [comment]
Closing this as it seems to be fixed, if it reoccurs then feel free to comment here instead of making a new issue.
