### ISSUE TITLE
voidcraft{0.13.4} crashes dedicated Forge 1.11.2 build 2223 on startup

### ISSUE THREAD

**Issue by kreezxil** [Tamaized/VoidCraft#82]
Notes:
     no class found error

crash report:
https://gist.github.com/8c5d47e9a151f5f568b91e94fbd41a28

fml server latest:
https://gist.github.com/00ba943137b797434769071436b37116

**Comment by Tamaized** [comment]
Whoops, not sure how that got past me, I'll get a fix out soon
