### ISSUE TITLE
Client crash -rendering LichInferno

### ISSUE THREAD

**Issue by ProsperCraft** [Tamaized/VoidCraft#83]
https://gist.github.com/ProsperCraft/a0b527244ee7233683802865f72e3ec8

voidcraft{0.13.5} [VoidCraft] (VoidCraft-1.11.2-0.13.5.jar

**Comment by Tamaized** [comment]
Are there any mods changing how things are rendered because there's 0 reason for this to crash.

**Comment by Tamaized** [comment]
I take that back, seems a few lines of code didn't get changed when they were supposed to. Getting a fix out now.
