### ISSUE TITLE
Entity max health being reported as 20 for alot of entities that should not be adjusted.

### ISSUE THREAD

**Issue by kragnoth** [Tamaized/VoidCraft#84]
Bat health: Normal max health 6
Bat health: Reported max health 20
Squids vanilla max: 10
Squids with voidcraft max: 20

I believe one of your methods might be overriding the vanilla getDefaultMaxhealth entity method.  I was looking at the code in the companion class, and believe it might be in there.  I tried compiling with changes to verify, but cannot get code to compile.  Will test again after I get compile working and report which method is causing.

**Comment by Tamaized** [comment]
Is this in the 1.11 versions? Or 1.10?

**Comment by kragnoth** [comment]
oh I'm sorry, 1.11.2.  I'm testing to see if I can find the method right now, got it to compile.  Probably a library dependency, but I've got it compiling now.

**Comment by kragnoth** [comment]
Cool, thanks.
