### ISSUE TITLE
1.10.2 Crash

### ISSUE THREAD

**Issue by MokahTGS** [Tamaized/VoidCraft#85]
http://pastebin.com/9ETX59n3

Not sure what's causing this...

**Comment by Tamaized** [comment]
Wow, ran out of IDs in 1.10, that's a first (Well, first for me to see anyway). I'm actually not really sure on what I can do here, I'll do a bit of research though to see if anything is possible on my end.

**Comment by Tamaized** [comment]
Yea, looking into it, the max Block and Item ID range is indeed 4096 and there's nothing I can do about it really.
