### ISSUE TITLE
[1.10.2] Broken textures

### ISSUE THREAD

**Issue by al132** [Tamaized/VoidCraft#86]
Voidcraft-1.10.2-0.13.7
TamModized-1.10.2-0.5.2

In the most recent version of Voidcraft for 1.10.2 all of the background textures for the vade mecum and JEI are broken. I took a quick peek at the code and it looks like it's related to the lowercasing of resource locations (because of 1.11 compatibility I assume) 

https://github.com/Tamaized/VoidCraft/blob/1.10.2/src/main/java/Tamaized/Voidcraft/GUI/client/VadeMecumGUI.java#L32

https://github.com/Tamaized/VoidCraft/blob/1.10.2/src/main/resources/assets/voidcraft/textures/gui/vademecum/vademecum.png

**Comment by Tamaized** [comment]
Hard to catch these in a dev workspace since they work for whatever reason, I got most at least. on it.

**Comment by Tamaized** [comment]
07d4b7f0e33880a32402d7dca83eb9dc14398532
