### ISSUE TITLE
Lingering MovementSpeed Reduction 

### ISSUE THREAD

**Issue by timbrown81** [Tamaized/VoidCraft#87]
I was playing this mod last night(single player) and made several trips to the void.  At some point Minecraft crashed. Afterwards, my movement speed got stuck in a reduced state.  I tried everything to clear the state, even putting all gear into a chest, killing myself and respawning.  I opened the save file and examined the NBT.  Under the movementSpeed attribute there was still a modifier with -0.75 and a name of "health speed penalty".  I deleted the modifier and loaded up the world and still had a reduce movementSpeed.  I again looked at the NBT and something had reapplied the modifier again.

**Comment by Tamaized** [comment]
Voidcraft doesn't do anything to movement speed. Did you have any other mods?

**Comment by timbrown81** [comment]
I have dozens of other mods.  I first was looking to Voidcraft as this was the first time I had travelled to the Void and I believed it was related to the infusion affect.

**Comment by Tamaized** [comment]
I would say it's another mod. Voidic infusion doesn't affect move speed attributes nor does the rest of the mod, the most the mod does is apply the slowness effect debuff from vanilla effects. But that's not the case here. Perhaps that crash report would give us some insight.

**Comment by timbrown81** [comment]
You are correct, it was another mod that I had installed yesterday.  Thanks for looking at that for me!
