### ISSUE TITLE
Shift-F3 crash

### ISSUE THREAD

**Issue by fscan** [Tamaized/VoidCraft#88]
Pressing Shift-F3 with VoidCraft installed (only mod next to TamModized) crashes Minecraft. Forge installation should be fine, other mods work as expected.

[crash-2017-02-14_23.21.05-client.txt](https://github.com/Tamaized/VoidCraft/files/775450/crash-2017-02-14_23.21.05-client.txt)

**Comment by Tamaized** [comment]
And is this anywhere or in a specific machine?

**Comment by fscan** [comment]
Sorry, forgot to specify. This is single player, i could test multiplayer tomorrow(ish). Only tested it on my machine (but with multiple minecraft instances), relevant specs should be in the crash log.

**Comment by Tamaized** [comment]
Oh it's fine, I already figured out the cause. Thanks for reminding me though as I've known about this one for a very long time but totally forgot it existed.
