### ISSUE TITLE
[1.10.2] More Missing Texture issues

### ISSUE THREAD

**Issue by Tamaized** [Tamaized/VoidCraft#89]

**Comment by DV666** [comment]
Missing texture on Chained Specter, Void Wrath and Lich (actually see that on Better Questing hunt task)

[Example with Lich on BQ](http://img11.hostingpics.net/pics/80340920170220000248.png)

**Comment by Tamaized** [comment]
And the issue is only on the Entities right, everything else seems good? such as Items/Blocks and GUIs

**Comment by Tamaized** [comment]
The English is fine, as for the missing textures.. based on what I discovered in my code it only affected 4 entities and I can see why I missed them too, just some oversights really. Fix is in I just need to upload it and wait for curse to approve the file, that may take some time sadly.

**Comment by DV666** [comment]
No problem for the waiting :) I will waiting this update and confirm with you if it's ok or not to close this issue.

Thanks for you quickness.

**Comment by Tamaized** [comment]
Yea I wont be closing this issue until we have confirmation.

**Comment by Tamaized** [comment]
[It's finally approved](https://minecraft.curseforge.com/projects/voidcraft/files/2383975)

**Comment by DV666** [comment]
Indeed and....

[Test with this fix](http://img11.hostingpics.net/pics/46910320170220011401.png)

[Conclusion](https://media.giphy.com/media/a3IWyhkEC0p32/giphy.gif)

**Comment by Tamaized** [comment]
Sweet
