### ISSUE TITLE
crash on server from entity (1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [Tamaized/VoidCraft#96]
forge:1.11.2-2252
voidcraft: VoidCraft-1.11.2-0.15.1
tamized: TamModized-1.11.2-0.6.2
crash report:
[crash-2017-03-03_14.41.06-server.txt](https://github.com/Tamaized/VoidCraft/files/817726/crash-2017-03-03_14.41.06-server.txt)

**Comment by Tamaized** [comment]
Welp TIL that EntityArrow#setVelocity is SideOnly(Client); Anyway this will also crash in 1.10.2, getting a fix out now.

**Comment by SDUBZ** [comment]
another crash @Tamaized 
voidcraft:  VoidCraft-1.11.2-0.15.2
crash report:
[crash-2017-03-03_16.01.28-server.txt](https://github.com/Tamaized/VoidCraft/files/817919/crash-2017-03-03_16.01.28-server.txt)

**Comment by Tamaized** [comment]
I actually JUST found this one as well myself and am questioning Mojang's choices with this retarded code they have. Already on it.

**Comment by SDUBZ** [comment]
okay :)

**Comment by Tamaized** [comment]
Let me know if 0.15.3 fixed it, I have a hunch I messed up and the jar got built before the change actually went through, im not sure if it did or not right now.
