### ISSUE TITLE
Can't connect on server with build 0.17.2

### ISSUE THREAD

**Issue by DV666** [Tamaized/VoidCraft#97]
I update my modpack with Voidcraft 0.17.2 => Update my server too but impossible to connect "Internal Server Error"
Same thing for my friends.

Downgrade to previous version 0.16.2 : work perfectly.

I will paste logs asap on this thread (lost previous logs woops so i try again on local server).
It's was an issue with NBT.

EDIT : Works perfectly on local server (.bat)... weird, i try again on my dedicated server.

EDIT2 : Still crash on my dedicated server 

> [13:09:11] [User Authenticator #1/INFO]: UUID of player DVlad is 39099fdf-0b43-4a85-98e5-7df7b25cfc28
> [13:09:15] [Server thread/WARN]: Failed to handle packet for [MASKED IP]
> net.minecraft.util.ReportedException: Loading entity NBT
> 	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1716) ~[rw.class:?]
> 	at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:222) ~[azy.class:?]
> 	at net.minecraft.server.management.PlayerList.func_72380_a(PlayerList.java:322) ~[mp.class:?]
> 	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:112) ~[mp.class:?]
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) ~[NetworkDispatcher.class:?]
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) ~[NetworkDispatcher.class:?]
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.IVadeMecumCapability$CategoryDataWrapper.<init>(IVadeMecumCapability.java:105) ~[IVadeMecumCapability$CategoryDataWrapper.class:?]
> 	at Tamaized.Voidcraft.vadeMecum.progression.VadeMecumWordsOfPower.<clinit>(VadeMecumWordsOfPower.java:60) ~[VadeMecumWordsOfPower.class:?]
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.IVadeMecumCapability.isActivePower(IVadeMecumCapability.java:123) ~[IVadeMecumCapability.class:?]
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.VadeMecumCapabilityHandler.setCurrentActive(VadeMecumCapabilityHandler.java:156) ~[VadeMecumCapabilityHandler.class:?]
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.VadeMecumCapabilityStorage.readNBT(VadeMecumCapabilityStorage.java:76) ~[VadeMecumCapabilityStorage.class:?]
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.VadeMecumCapabilityStorage.readNBT(VadeMecumCapabilityStorage.java:14) ~[VadeMecumCapabilityStorage.class:?]
> 	at Tamaized.Voidcraft.capabilities.EventHandler$2.deserializeNBT(EventHandler.java:74) ~[EventHandler$2.class:?]
> 	at Tamaized.Voidcraft.capabilities.EventHandler$2.deserializeNBT(EventHandler.java:53) ~[EventHandler$2.class:?]
> 	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:133) ~[CapabilityDispatcher.class:?]
> 	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1690) ~[rw.class:?]
> 	... 13 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.IVadeMecumCapability$CategoryDataWrapper.<init>(IVadeMecumCapability.java:105) ~[IVadeMecumCapability$CategoryDataWrapper.class:?]
> 	at Tamaized.Voidcraft.vadeMecum.progression.VadeMecumWordsOfPower.<clinit>(VadeMecumWordsOfPower.java:60) ~[VadeMecumWordsOfPower.class:?]
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.IVadeMecumCapability.isActivePower(IVadeMecumCapability.java:123) ~[IVadeMecumCapability.class:?]
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.VadeMecumCapabilityHandler.setCurrentActive(VadeMecumCapabilityHandler.java:156) ~[VadeMecumCapabilityHandler.class:?]
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.VadeMecumCapabilityStorage.readNBT(VadeMecumCapabilityStorage.java:76) ~[VadeMecumCapabilityStorage.class:?]
> 	at Tamaized.Voidcraft.capabilities.vadeMecum.VadeMecumCapabilityStorage.readNBT(VadeMecumCapabilityStorage.java:14) ~[VadeMecumCapabilityStorage.class:?]
> 	at Tamaized.Voidcraft.capabilities.EventHandler$2.deserializeNBT(EventHandler.java:74) ~[EventHandler$2.class:?]
> 	at Tamaized.Voidcraft.capabilities.EventHandler$2.deserializeNBT(EventHandler.java:53) ~[EventHandler$2.class:?]
> 	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:133) ~[CapabilityDispatcher.class:?]
> 	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1690) ~[rw.class:?]
> 	... 13 more
> [13:09:15] [Server thread/INFO]: DVlad lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
> [13:09:15] [Server thread/INFO]: DVlad left the game
> [13:09:23] [Server thread/INFO]: Stopping the server
> [13:09:23] [Server thread/INFO]: Stopping server
> [13:09:23] [Server thread/INFO]: Saving players
> [13:09:23] [Server thread/INFO]: Saving worlds
> [13:09:23] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
> [13:09:24] [Server thread/INFO]: Saving chunks for level 'world'/Nether
> [13:09:24] [Server thread/INFO]: Saving chunks for level 'world'/The End
> [13:09:24] [Server thread/INFO]: Saving chunks for level 'world'/Deep Dark
> [13:09:24] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
> [13:09:24] [Server thread/INFO]: Saving chunks for level 'world'/ExtraUtils2_Quarry_Dim
> [13:09:24] [Server thread/INFO]: Saving chunks for level 'world'/The Void
> [13:09:25] [Server Shutdown Thread/INFO]: Stopping server
> [13:09:25] [Server Shutdown Thread/INFO]: Saving players
> [13:09:25] [Server Shutdown Thread/INFO]: Saving worlds

**Comment by Tamaized** [comment]
I'll get a fix out soon

**Comment by DV666** [comment]
Nice, thanks again for your efficiency :) I will wait.

**Comment by Tamaized** [comment]
would have gotten to it sooner but I just now woke up hehe ;)
