### ISSUE TITLE
Missing textures on somes machines + twinkling Voidic Power on Blast Furnace (build 0.16.2)

### ISSUE THREAD

**Issue by DV666** [Tamaized/VoidCraft#99]
Hi Tamaized... it's me again :o)

Version used : 0.16.2 (not update the last yet on my server...)

One of my player on my private server have some issues with HUD on theses machines (he didn't use any ressources pack) :
- Void Infuser
- Void Infused Macerator

Somes screenshoots for you : 
Void Infuser : [Here !](http://img4.hostingpics.net/pics/24197120170311122402.png)
Void Infused Macerator : [Here !](http://img4.hostingpics.net/pics/17131920170311122343.png)

Moreover, another issue with the Void Blast Furnace : when the voidic power is filling/draining, the amount is twinkling very quickly.

That's all ! :) Available for more informations if you need.

PS : He likes your mod :D 
PS2 : If you want a little feature, it's possible to add a new armor between Void and Xia ?

**Comment by Tamaized** [comment]
I'll look into this all now, as for the armor, there's going to be more content added post-Xia (I've already started on it) but there won't be a new set of armor between the current ones.

**Comment by Tamaized** [comment]
Is it possible for you to give me an example on what you mean by "the amount is twinkling very quickly" as i'm not quite sure what the issue is.

On a side note, the texture issue is fixed here: 0b78be03755ceb1f4a7a680a72c11bd1fac5afa0 and the build will go out once i'm done fixing the last issue.

**Comment by DV666** [comment]
Here is a exemple about this twinkling issue ^^

[Bug record](https://www.youtube.com/watch?v=NM0yWKFNLSw&feature=youtu.be)

But that's weird because work perfectly on solo and try to test a new one on creative mode (same server) : work too... I don't know why his blast furnace react like this ^^

**Comment by Tamaized** [comment]
Thanks, that actually helps quite a bit, i'll look for what's causing this.

**Comment by Tamaized** [comment]
I assume you already tried to break and replace his blast furnace? and that it didn't work?

**Comment by DV666** [comment]
I assume too but he didn't replace the blast furnace so he did that and now it's work perfectly... sorry for the trouble :( I think you can close the case.

**Comment by Tamaized** [comment]
Sweet, yea not sure what exactly caused the issue, something weird must have happened with how the NBT was being saved with the tile entity, replacing will fix it as it did.
